export const FETCH_CURRENCY = 'FETCH_CURRENCY';
export const FROM_CHANGE_INPUT = 'FROM_CHANGE_INPUT';
export const TO_CHANGE_INPUT = 'TO_CHANGE_INPUT';
export const FROM_CURRENCY_CHANGE = 'FROM_CURRENCY_CHANGE';
export const TO_CURRENCY_CHANGE = 'TO_CURRENCY_CHANGE';
export const HANDEL_ERROR = 'HANDEL_ERROR';
export const SWITCH_BETWEEN = 'SWITCH_BETWEEN';


export const LATEST_RE = "LATEST_RE";
export const LATEST_SUCCESS = "LATEST_SUCCESS";
export const LASTEST_FAIL = "LASTEST_FAIL";